repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.12
  hooks:
    # Run the linter.
    - id: ruff-check
    # Run the formatter.
    - id: ruff-format
    
- repo: local
  hooks:
    - id: pytest-fast
      name: "Run Fast Tests"
      description: "Run only fast tests before committing"
      entry: pytest
      language: system
      files: ^(tests/.*\.py|.*test.*\.py|test_.*\.py)$
      args: [
        "-v",
        "-m", "not slow",      # Skip tests marked as @pytest.mark.slow
        "--tb=line",           # Even shorter traceback
        "--disable-warnings",
        "-x"                   # Stop on first failure
      ]
